import { Metadata } from "next";
import "./global.css";

export const metadata: Metadata = {
  // <title>
  title: "Next",
  // 与 <link> 相关
  /**
   * metadataBase https://beta.nextjs.org/docs/api-reference/metadata#metadatabase
   */
  // metadataBase: new URL("https://www.xxx.com"),
  // alternates: {},
  // icons: {},
  // archives: "",
  // assets: "",
  // bookmarks: "",
  // 与 <meta> 相关
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1", // 会自动添加
  applicationName: "",
  // 混合
  authors: [],
  other: {

  }
}

export default function RootLayout({ children }: {
  children: React.ReactNode,
}) {
  return (
    <html lang="en">
      {/* <head>
        <style />
      </head> */}
      <body className="body">{children}</body>
    </html>
  );
}