import Link from "next/link";
import type { Metadata } from 'next';
import Script from 'next/script'
import styles from "./styles.module.css";

export const metadata: Metadata = {
  title: "Next App Dir App",
  description: "Generated by create next app",
  // viewport: "width=device-width, initial-scale=1", // 会自动添加
}

export default function HomePage() {
  return (
    <>
      {/* script 标签使用，根据src属性自动去重 */}
      <Script key="1" src="//cdn.jsdelivr.net/npm/eruda" />
      {/* <Script key="2" src="//cdn.jsdelivr.net/npm/eruda?a=2" /> */}
      <main className={styles.main}>
        <h2>页面列表</h2>
        <ul>
          <li>
            <Link href="/features/metadata">metadata</Link>
          </li>
        </ul>
      </main>
    </>
  );
}
